modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="warheads"
version="0.0.1"
displayName="Warheads"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="hacke, MCreator"
description='''
Фантазия да и только
'''

[[dependencies.warheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




